
@startuml

class Game {
    - players: List<BasePlayer>
    - max_steps: int
    - current_step: int
    --
    + play_round()
    + run_game()
}

abstract class BasePlayer {
    - name: str
    - balance: int
    --
    + make_bet()
}

class MartingaleBot {
    + make_bet()
}

class PercentageBot {
    + make_bet()
}

class PassiveAggressiveBot {
    + make_bet()
}

Game *-- BasePlayer
BasePlayer <|-- MartingaleBot
BasePlayer <|-- PercentageBot
BasePlayer <|-- PassiveAggressiveBot

@enduml
