name: Run Tests

on:
  push:
    branches:
      - main
      - linear_algebra
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.6'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest mypy

      - name: Run tests
        run: |
          pytest
